version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "4506:3306"
    environment:
      - MYSQL_DATABASE=elearning_seiya_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql:rw
    command: --innodb_use_native_aio=0
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/elearning_seiya
    ports:
      - "3004:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
